[app]
name = "My Conf. Badge"
category = "Badge"
wifi_preference = true

[entry]
class = "ConferenceBadge"

[metadata]
author = "JonTheNiceGuy"
license = "Unlicense"
url = "https://github.com/JonTheNiceGuy/tildagon-my-conference-badge"
description = "A configurable \"My name is\" conference badge with the option to add your own custom pages of details, plus the ability to add your own image and \"In Case of Emergency\" (ICE) details. You configure the badge using a web interface."
version = "1.5.0"
